### ISSUE TITLE
Input for mpview

### ISSUE THREAD

**Issue by xavhl** [atlantis-ar/matterport_utils#1]
First of all thank you so much for developing the utils programs!

May I ask what the expected inputs are for mpview with -seg_maps option?

I fed in following options but the segmentation output were images with noise pixels. 

- -input_house 
- -input_scene 
- -input_mesh 
- -input_categories 
- -input_segments 
- -input_objects 
- -input_configuration 
- -output_image 

![00ebbf3782c64d74aaf7dd39cd561175_c2_0](https://user-images.githubusercontent.com/50361174/147277669-75a3107f-33ad-4481-818b-4e439e127f18.png)
![00ebbf3782c64d74aaf7dd39cd561175_c2_0](https://user-images.githubusercontent.com/50361174/147402446-c9891446-5267-4186-bf6f-6a8e7a0d6801.png)

May you kindly advise? Thank you!

**Comment by wbailer** [comment]
Here is a working example, the window size should probably be specified (having the additional inputs should not harm, but you can try dropping them):

-input_house house_segmentations/1LXtFkjw3qL.house -input_mesh house_segmentations/1LXtFkjw3qL.ply -input_segments house_segmentations/1LXtFkjw3qL.fsegs.json -input_objects house_segmentations/1LXtFkjw3qL.semseg.json -window 1280 1024 -output_image my_segmentation_maps -v

Hope this fixes the issue with the noisy output.

**Comment by xavhl** [comment]
Thank you so much for the instructions! It works like a charm now
